### ISSUE TITLE
Does it work on banana pi zero board?

### ISSUE THREAD

**Issue by InfVRN** [PaulJenkin/PS4RaspberryPi#11]
Hello from Russia.First - thank you, for this project. Its really cool!!. In descriprion on aliexpress told about  compatibility banana pi m2 zero, with rasberry pi zero images. Will this host work on this board? This boand is cheaper, than pi board. Thanks for answer and sorry for my english(

**Comment by PaulJenkin** [comment]
by default it will not work as these are custom built of raspberry Pi, but using build root we can build one for banana pi well

**Comment by InfVRN** [comment]
I can buy this board and test it with my ps4. Os on banana pi is here: https://wiki.banana-pi.org/Banana_Pi_BPI-M2_ZERO 
Can you look

**Comment by PaulJenkin** [comment]
with Banana_Pi_BPI-M2_ZERO we can only do a blind development, i can develop but the chance of working is very less.
Pi Zero W should be a cheaper option i believe

**Comment by InfVRN** [comment]
Thanks for answer. Yep, better buy pi ZeroW board.
