### ISSUE TITLE
V8 PiZ2W Image not booting

### ISSUE THREAD

**Issue by d3structor84** [PaulJenkin/PS4RaspberryPi#13]
Hello.

Image for Pi Zero 2 W seems broken with last update.
It keeps rebooting on 2 different Devices with 2 different SD-Cards.

Pi Zero W works flawless.
Can't tell about RPi4B.

Greetings

**Comment by PaulJenkin** [comment]
Hi
Links for rebuild 4 has been updated which fixs the boot issue, please try it and see if its good
