### ISSUE TITLE
Not pop up the USB drive.

### ISSUE THREAD

**Issue by langerst** [PaulJenkin/PS4RaspberryPi#24]
it's not pop up the USB drive after notice came say wating.....blabla....anything more I should do?.......or any place setting I can check....?

**Comment by langerst** [comment]
V10 RsZW trying many times.....

**Comment by PaulJenkin** [comment]
What Device you using?

1. If Pi Zero W or Pi Zero 2 W, the micro USB cable has to be in USB Slot, All not all USB wires support Data transfer, some wires are just for power, Try with different wires

**Comment by langerst** [comment]
thanks for reply, Pi ZeroW using the USB slot, the cable tested with gamepad working with data. Im thinking about the port broken?......or some setting need to be reset on Pi bios.....

**Comment by langerst** [comment]
Starting php-fpm
done
etc/init.d/rcS: line 23: /etc/init.d/S50avahi-daemon: Permission denied
Starting nginx.
Starting sshd: OK
Starting dnsmasq: OK
Starting hostapd: Configuration file: retc/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:b:8c:ba:34 and ssid "PiZero"
wlan0: interface state UNINITIALIZED-›ENABLED
wlan0: AP-ENABLED
OK
Starting pyFTPServer OK
nohup: appending output to nohup. out
/etc/init.d/rcS: line 23: etc/init.d/S99IdelTimer: Permission denied
Welcome to PiZero
pizero login:

**Comment by langerst** [comment]
`Starting php-fpm
done
etc/init.d/rcS: line 23: /etc/init.d/S50avahi-daemon: Permission denied
Starting nginx.
Starting sshd: OK
Starting dnsmasq: OK
Starting hostapd: Configuration file: retc/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:b:8c:ba:34 and ssid "PiZero"
wlan0: interface state UNINITIALIZED-›ENABLED
wlan0: AP-ENABLED
OK
Starting pyFTPServer OK
nohup: appending output to nohup. out
/etc/init.d/rcS: line 23: etc/init.d/S99IdelTimer: Permission denied
Welcome to PiZero
pizero login:`
