### ISSUE TITLE
Raspberry Pi 3b+

### ISSUE THREAD

**Issue by mahay030882** [PaulJenkin/PS4RaspberryPi#40]
It will possible support for the 3B/3B+?

Thanks in advance.

**Comment by Stefan300381** [comment]
in deed I was disappointed to see that you limit your project to full image files rather than source, for compiling myself on any desired target platform. anyway, nice job!

**Comment by USL5264** [comment]
Can this work on a model 3b+?

**Comment by n3mur1t0r** [comment]
This will only work Pi Zero, Pi Zero 2 or 4B (or possibly Pi Pico as well?) simply because these are the only Pi's having OTG capabilities.

**Comment by PaulJenkin** [comment]
Closing this issue as 3b+ doesn't have OTG
