### ISSUE TITLE
Updating JB files. 

### ISSUE THREAD

**Issue by JasonDistler** [PaulJenkin/PS4RaspberryPi#7]
i have enabled SSH and am able to connect via wifi but cannot figure out where you are keeping the JB files for the server. I want to be able to keep this updated

**Comment by PaulJenkin** [comment]
i understand the problem
the other way of doing it is update the data in SD card after its written (root user)

didn't add ssh as it was interfering with Apache/nginx , now i have isolated that issue, as i have already finalised the V5 version, will include the SSH Changes on V6

**Comment by JasonDistler** [comment]
unless you can add samba like server to remote access JB folders

**Comment by PaulJenkin** [comment]
Good idea will try do add in upcoming version

**Comment by PaulJenkin** [comment]
Version 6 is uploaded which has the option to connect to local network

**Comment by PaulJenkin** [comment]
Closing this as primary objective is reached
