### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by megaoctet** [PaulJenkin/PS4RaspberryPi#8]
https://odysee.com/@megaoctet:5/ps4_9.00_PiZero2W:8

Hello,
I made a small video because I started to talk about your work on a French site where I am a member "logic-sunrise.fr".
The little video is to show the use of this technique via the raspberrypi.
If you don't want me to diffuse this video, if it doesn't suit you and if you want me to delete it, tell me.
There will be no problem.
Congratulations to you as you can see in the video it works perfectly for me with the V5 image
Bye 

Translated with www.DeepL.com/Translator (free version)

**Comment by PaulJenkin** [comment]
No issue, you can have the video
